name: Android Instrumented Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  instrumented-tests:
    name: Run Instrumented Tests
    runs-on: macos-latest  

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Instrumented Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30                
          target: google_apis         
          arch: x86_64                 
          profile: pixel_4             
          script: ./gradlew connectedAndroidTest


      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-test-reports
          path: app/build/reports/androidTests/connected/
