name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Set up Android SDK
      uses: reactivecircus/android-sdk-install@v3
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Install dependencies
      run: ./gradlew --no-daemon clean build

    - name: Run instrumented tests
      run: ./gradlew --no-daemon connectedDebugAndroidTest
