name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [30]
        target: ["google_apis"]
        arch: ["arm64-v8a"]  # Используем ARM64 вместо x86

    steps:
      # 1. Скачивание кода
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Установка JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      # 3. Установка Android SDK вручную
      - name: Install Android SDK
        run: |
          curl -O https://dl.google.com/android/repository/commandlinetools-mac-12266719_latest.zip
          unzip commandlinetools-mac-12266719_latest.zip -d $HOME/Library/Android/sdk/cmdline-tools
          echo "ANDROID_HOME=$HOME/Library/Android/sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/Library/Android/sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

      # 4. Принимаем лицензии SDK
      - name: Accept Android SDK licenses
        run: yes | $HOME/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      # 5. Установка Android Emulator
      - name: Install Emulator
        run: $HOME/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager "emulator" "platform-tools" "system-images;android-30;google_apis;arm64-v8a"

      # 6. Запуск Android эмулятора
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: arm64-v8a  # Указываем ARM64 архитектуру
          profile: pixel_3a
          emulator-options: "-no-snapshot -no-boot-anim"
          force-avd-creation: true
          emulator-boot-timeout: 600
          emulator-port: 5554
          disable-animations: true
          script: |
            adb wait-for-device
            # Ждем 30 секунд для полной загрузки эмулятора
            sleep 30
            # Проверяем доступность устройства
            adb devices
            adb shell input keyevent 82  # Разблокировать экран

      # 7. Запуск тестов
      - name: Run Tests
        run: ./gradlew connectedAndroidTest

      # 8. Загрузка результатов тестов
      - name: Upload Test Results
        if: always()  # Загрузка результатов независимо от успеха или ошибки тестов
        uses: actions/upload-artifact@v4
        with:
          name: android-test-results
          path: app/build/reports/androidTests/connected/
