name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Install Android SDK
        run: |
          echo "Setting up Android SDK..."
          rm -rf $HOME/Library/Android/sdk ~/.android
          mkdir -p $HOME/Library/Android/sdk/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-mac-10406996_latest.zip
          unzip -q commandlinetools.zip -d $HOME/Library/Android/sdk/cmdline-tools
          mv $HOME/Library/Android/sdk/cmdline-tools/cmdline-tools $HOME/Library/Android/sdk/cmdline-tools/latest

          export ANDROID_HOME=$HOME/Library/Android/sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --no_https || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update --no_https || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "build-tools;35.0.0" \
            "platform-tools" \
            "platforms;android-30" \
            "system-images;android-30;google_apis;arm64-v8a" \
            "emulator" --no_https || true

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: "google_apis"
          arch: "arm64-v8a"
          profile: pixel_3a
          emulator-options: "-no-snapshot -no-boot-anim -gpu swiftshader_indirect -accel off"
          force-avd-creation: true
          emulator-boot-timeout: 600
          disable-animations: true

      - name: Wait for Emulator Boot
        run: |
          adb start-server
          for i in {1..60}; do
            boot_completed=$(adb -s emulator-5554 shell getprop sys.boot_completed | tr -d '\r')
            if [ "$boot_completed" == "1" ]; then
              echo "Emulator booted successfully!"
              break
            fi
            echo "Waiting for emulator to boot... Attempt $i"
            sleep 10
          done
          if [ "$boot_completed" != "1" ]; then
            echo "Emulator failed to boot!"
            exit 1
          fi

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.itog1.ExampleInstrumentedTest

      - name: Terminate Emulator
        run: |
          echo "Terminating emulator..."
          adb devices | grep emulator-5554 && adb -s emulator-5554 emu kill || echo "Emulator not running."
