name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [30]
        target: ["google_apis"]
        arch: ["arm64-v8a"]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Install Android SDK
        run: |
          echo "Cleaning up any existing SDK..."
          rm -rf $HOME/Library/Android/sdk ~/.android
          mkdir -p $HOME/Library/Android/sdk/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-mac-10406996_latest.zip
          unzip -q commandlinetools.zip -d $HOME/Library/Android/sdk/cmdline-tools
          mv $HOME/Library/Android/sdk/cmdline-tools/cmdline-tools $HOME/Library/Android/sdk/cmdline-tools/latest

          export ANDROID_HOME=$HOME/Library/Android/sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --no_https
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update --no_https
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "build-tools;35.0.0" \
            "platform-tools" \
            "platforms;android-30" \
            "system-images;android-30;google_apis;arm64-v8a" \
            "emulator"

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: pixel_3a
          emulator-options: "-no-snapshot -no-boot-anim -wipe-data -gpu host"
          force-avd-creation: true
          emulator-boot-timeout: 300
          disable-animations: true
          script: |
            adb wait-for-device
            sleep 30
            adb shell input keyevent 82  # разблокировка экрана

      - name: Restart adb server
        run: |
          adb kill-server
          adb start-server
          adb wait-for-device
          sleep 30

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.itog1.ExampleInstrumentedTest

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-test-results
          path: app/build/reports/androidTests/connected/
