name: Android Instrumented Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  instrumented-tests:
    name: Run Instrumented Tests
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [30]
        target: [google_apis]
        arch: [arm64-v8a]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Update SDK and install system image
        run: |
          sdkmanager --update
          sdkmanager "system-images;android-30;google_apis;arm64-v8a" "emulator"

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: pixel_4
          disable-animations: true
          enable-hardware-keyboard: true

      - name: Wait for Emulator
        run: adb wait-for-device

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-results
          path: app/build/reports/androidTests/connected/
