name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [30]
        target: ["google_apis"]
        arch: ["x86"]

    steps:
      # 1. Скачивание кода
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Установка JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      # 3. Установка Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
      
      # 4. Запуск Android эмулятора
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: pixel_3a
          emulator-options: "-no-snapshot -no-boot-anim -no-hw-accel"
          force-avd-creation: true
          emulator-boot-timeout: 600
          emulator-port: 5554
          disable-animations: true
          emulator-build: "true"
          script: |
            adb wait-for-device
            adb shell input keyevent 82  # Разблокировать экран

      # 5. Запуск тестов
      - name: Run Tests
        run: ./gradlew connectedAndroidTest

      # 6. Загрузка результатов тестов
      - name: Upload Test Results
        if: always()  # Загрузка результатов независимо от успеха или ошибки тестов
        uses: actions/upload-artifact@v4
        with:
          name: android-test-results
          path: app/build/reports/androidTests/connected/
