name: Android Instrumented Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  instrumented-tests:
    name: Run Instrumented Tests
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [30]
        target: [default]
        arch: [x86]

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK components
        run: sdkmanager "system-images;android-30;default;x86"

      - name: Restart ADB Server
        run: |
          adb kill-server
          adb start-server
          adb devices

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: pixel_4
          script: |
            emulator -avd pixel_4 -no-window -gpu off &
            adb wait-for-device
            sleep 60
            adb devices
            ./gradlew connectedAndroidTest

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-results
          path: app/build/reports/androidTests/connected/
