name: Run Android Emulator

on:
  push:
    branches:
      - main

jobs:
  android-emulator:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Android SDK
      run: |
        yes | sdkmanager --licenses
        sdkmanager --install 'build-tools;35.0.0' platform-tools 'platforms;android-30' emulator --channel=0
        sdkmanager --install 'system-images;android-30;google_apis;arm64-v8a' --channel=0

    - name: Create AVD
      run: |
        echo no | avdmanager create avd --force -n test --abi 'google_apis/arm64-v8a' --package 'system-images;android-30;google_apis;arm64-v8a' --device 'pixel_3a'
        echo "hw.cpu.ncore=2" >> /Users/runner/.android/avd/test.avd/config.ini

    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: arm64-v8a
        profile: pixel_3a
        emulator-options: "-no-snapshot -no-boot-anim -gpu swiftshader_indirect -wipe-data -accel off -no-vulkan"
        force-avd-creation: true
        emulator-boot-timeout: 1200

    - name: Wait for emulator to boot
      run: |
        echo "Waiting for the emulator to boot..."
        adb wait-for-device
        adb shell getprop sys.boot_completed | grep "1" > /dev/null
        echo "Emulator booted successfully!"

    - name: Run tests
      run: |
        # Run your tests here
        echo "Running tests"
