name: Run Android Emulator

on:
  push:
    branches:
      - main

jobs:
  android-emulator:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Android SDK and accept licenses
      run: |
        curl -s https://dl.google.com/android/repository/commandlinetools-mac-8512546_latest.zip -o commandlinetools.zip
        unzip commandlinetools.zip -d $HOME/Android
        rm commandlinetools.zip
        mkdir -p $HOME/Android/Sdk/cmdline-tools/latest
        mv $HOME/Android/cmdline-tools/* $HOME/Android/Sdk/cmdline-tools/latest
        echo "export ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/emulator:$PATH" >> $GITHUB_ENV
        source $GITHUB_ENV
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install 'build-tools;35.0.0' platform-tools 'platforms;android-30' emulator
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install 'system-images;android-30;google_apis;arm64-v8a' --channel=0

    - name: Create AVD
      run: |
        echo no | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd --force -n test --abi 'google_apis/arm64-v8a' --package 'system-images;android-30;google_apis;arm64-v8a' --device 'pixel_3a'
        echo "hw.cpu.ncore=2" >> /Users/runner/.android/avd/test.avd/config.ini

    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: arm64-v8a
        profile: pixel_3a
        emulator-options: "-no-snapshot -no-boot-anim -gpu swiftshader_indirect -wipe-data -accel off -no-vulkan"
        force-avd-creation: true
        emulator-boot-timeout: 1200

    - name: Wait for emulator to boot
      run: |
        echo "Waiting for the emulator to boot..."
        adb wait-for-device
        adb shell getprop sys.boot_completed | grep "1" > /dev/null
        echo "Emulator booted successfully!"

    - name: Run instrumented tests
      run: |
        ./gradlew connectedAndroidTest -Pandroid.emulator.absoluteDir=/Users/runner/.android/avd/test.avd

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: android-test-results
        path: app/build/reports/androidTests/connected

    - name: Check if tests passed
      run: |
        if [ -f "app/build/reports/androidTests/connected/index.html" ]; then
          echo "Test results are available."
        else
          echo "No test results found. Please check the test configuration."
          exit 1
        fi
