name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [30]
        target: ["google_apis"]
        arch: ["x86_64"]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Install Android SDK
        run: |
          curl -O https://dl.google.com/android/repository/commandlinetools-mac-12266719_latest.zip
          unzip commandlinetools-mac-12266719_latest.zip -d $HOME/Library/Android/sdk/cmdline-tools
          mv $HOME/Library/Android/sdk/cmdline-tools/cmdline-tools $HOME/Library/Android/sdk/cmdline-tools/latest
          echo "ANDROID_HOME=$HOME/Library/Android/sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/Library/Android/sdk/cmdline-tools/latest/bin:$HOME/Library/Android/sdk/platform-tools" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: yes | $HOME/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Emulator and Dependencies
        run: |
          sdkmanager --update
          sdkmanager --install "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: pixel_3a
          emulator-options: "-no-snapshot -no-boot-anim -gpu swiftshader_indirect -accel off"
          force-avd-creation: true
          emulator-boot-timeout: 600

      - name: Wait for Emulator Boot
        run: |
          boot_completed=false
          for i in {1..30}; do
            if adb -s emulator-5554 shell getprop sys.boot_completed | grep -q "1"; then
              boot_completed=true
              break
            fi
            sleep 10
          done
          if [ "$boot_completed" = false ]; then
            echo "Emulator failed to boot."
            exit 1
          fi

      - name: Run Tests
        run: ./gradlew connectedAndroidTest --max-workers=2 --continue --no-daemon --info

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-results
          path: app/build/reports/androidTests/connected/*
