name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [30]
        target: ["google_apis"]
        arch: ["arm64-v8a"]

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Check out code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      # Шаг 3: Устанавливаем Android SDK и необходимые компоненты
      - name: Install Android SDK
        run: |
          echo "Installing Android SDK components..."
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-mac-10406996_latest.zip
          unzip -q commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager --install "build-tools;35.0.0" "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;arm64-v8a" "emulator"

      # Шаг 4: Запускаем эмулятор
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: pixel_3a
          emulator-options: "-no-snapshot -no-boot-anim -gpu swiftshader_indirect -wipe-data -accel off"
          force-avd-creation: true
          emulator-boot-timeout: 600
          script: |
            echo "Waiting for the emulator to boot..."
            adb wait-for-device
            adb shell getprop sys.boot_completed | grep "1" > /dev/null
            echo "Emulator booted successfully!"

      # Шаг 5: Запускаем инструментальные тесты
      - name: Run Instrumented Tests
        run: |
          echo "Running instrumented tests..."
          ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.itog1.ExampleInstrumentedTest

      # Шаг 6: Загружаем результаты тестов
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-test-results
          path: app/build/reports/androidTests/connected/

      # Шаг 7: Завершаем эмулятор
      - name: Terminate Emulator
        if: always()
        run: |
          echo "Stopping emulator..."
          adb devices | grep emulator-5554 && adb -s emulator-5554 emu kill || echo "Emulator not running."
